---
title: "Covers of majors"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Benchmarking de la implementación de politicas sustentables

En este trabajo analizaremos que desempeño de los intendentes del municipio (las acciones conjuntas que llevan los municipios de Maipu, Las Heras, Ciudad,...)

```{r}
co2 <- rnorm(50,200,30)
hist(co2)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Participación de cada municipio

```{r}
muni <- c("capital","godoy cruz","guaymallén","maipu","luján","las heras")
munico2 <- c(300,250,270,320,412,330)
pie(munico2, labels = muni)
```

### Transporte público

```{r}

```

RSU (Residuos Sólidos Urbanos) 
===
```{r}

```

Reciclado 
===
```{r}

```

RAE (Residuos de Aparatos Eléctricos) 
===
```{r}

```

